name: Sync dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  push:
    paths:
      - .github/actions/sync-dependency/**
      - .github/workflows/sync-dependencies.yml

jobs:
  sync-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Sync caveman
        uses: ./.github/actions/sync-dependency
        with:
          source-repo-url: https://github.com/JuliusBrussee/caveman
          source-slug: JuliusBrussee/caveman
          target-dir: skills/caveman
          use-tags: false
          mappings: |
            skills/*:.
            LICENSE:LICENSE
            agents:cavecrew/agents

      - name: Sync superpowers
        uses: ./.github/actions/sync-dependency
        with:
          source-repo-url: https://github.com/obra/superpowers
          source-slug: obra/superpowers
          target-dir: skills/superpowers
          use-tags: false
          mappings: |
            skills/*:.
            LICENSE:LICENSE
